# Generated by Django 5.2 on 2026-03-06 11:45

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название изображения для отображения в админке', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание (опционально)', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок сортировки (управляется drag&drop в админке)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать изображение в слайдере', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Загрузите изображение для слайдера через django-filer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдера',
                'ordering': ['order'],
            },
        ),
    ]
